wtf GitHub actions can't use Go 1.25?
Let's see if downgrading from go 1.25 to go 1.24 fixes the errors.

From the logs:
Run go test . -coverprofile=coverage -race
  go test . -coverprofile=coverage -race
  shell: /usr/bin/bash -e {0}
  env:
    GOTOOLCHAIN: local
go: go.mod requires go >= 1.25 (running go 1.24.7; GOTOOLCHAIN=local)
Error: Process completed with exit code 1.